global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'metrics-demo'
    static_configs:
      - targets: ['metrics-demo:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
